### ISSUE TITLE
shub_nacho_bl.bin error

### ISSUE THREAD

**Issue by 0x454447415244** [a2XX-dev/android_kernel_samsung_a21s#1]
Hi, there is something missing in the sensorhub firmware directory. I'm getting the below error:

```
  Using /mnt/SHARED/Phone/Samsung/A21S/gsi/kernel/android_kernel_samsung_a21s-master as source for kernel
  CALL    /mnt/SHARED/Phone/Samsung/A21S/gsi/kernel/android_kernel_samsung_a21s-master/scripts/checksyscalls.sh
  CHK     include/generated/compile.h
  SKIPPED include/generated/compile.h
make[2]: *** No rule to make target 'firmware/sensorhub/shub_nacho_bl.bin', needed by 'firmware/sensorhub/shub_nacho_bl.bin.gen.o'.  Stop.
make[1]: *** [/mnt/SHARED/Phone/Samsung/A21S/gsi/kernel/android_kernel_samsung_a21s-master/Makefile:1153: firmware] Error 2
make[1]: Leaving directory '/mnt/SHARED/Phone/Samsung/A21S/gsi/kernel/build'
make: *** [Makefile:149: sub-make] Error 2
```

Any idea?

Edit:
All of the below in the Makefile are not available:
fw-external-$(CONFIG_SENSORS_SSP) += sensorhub/shub_nacho_bl.bin
fw-external-$(CONFIG_SENSORS_SSP_A21S) += sensorhub/shub_nacho_a21s.bin 
fw-external-$(CONFIG_SENSORS_SSP_A21S) += sensorhub/a21s_bring_up.bin
fw-external-$(CONFIG_TOUCHSCREEN_SYNAPTICS_TCM) += tsp_synaptics/td4150_a21s.bin
fw-external-$(CONFIG_TOUCHSCREEN_HIMAX_CHIPSET) += tsp_himax/hx83112a_a21s.bin

**Comment by 0x454447415244** [comment]
@yukosky why you closed this issue?
I commented the above lines from the Makefile. It builds successfully but the phone doesn't boot properly.

**Comment by yukosky** [comment]
> @yukosky why you closed this issue?
> I commented the above lines from the Makefile. It builds successfully but the phone doesn't boot properly.

I'm doing bring-up from another kernel.

**Comment by 0x454447415244** [comment]
Can you please guide me on how to fix it? What is the other kernel?

**Comment by yukosky** [comment]
> Can you please guide me on how to fix it? What is the other kernel?

Not for now, I'm building one right now.

**Comment by 0x454447415244** [comment]
I'm trying to build a permissive SELINUX kernel by default. Do you have a prebuilt one that you can share?

**Comment by yukosky** [comment]
> I'm trying to build a permissive SELINUX kernel by default. Do you have a prebuilt one that you can share?

Nope :/

**Comment by 0x454447415244** [comment]
So this repo doesn't yet yield a working kernel?

**Comment by yukosky** [comment]
> So this repo doesn't yet yield a working kernel?

I necessarily stopped solving the problems of this kernel, so I am doing another one. I got more excited when I saw your issue.

**Comment by 0x454447415244** [comment]
What are the problems? I might be able to help...

**Comment by yukosky** [comment]
> What are the problems? I might be able to help...

I don't remember but check your issue again, you deleted .fw file to compile the kernel?

**Comment by yukosky** [comment]
```
MK_FW   firmware/sensorhub/shub_nacho_bl.bin.gen.S
MK_FW   firmware/sensorhub/shub_nacho_a21s.bin.gen.S
MK_FW   firmware/sensorhub/a21s_bring_up.bin.gen.S
MK_FW   firmware/tsp_synaptics/td4150_a21s.bin.gen.S
MK_FW   firmware/tsp_himax/hx83112a_a21s.bin.gen.S
CC      firmware/spu_verify/spu-sign-verify.o
AR      firmware/spu_verify/built-in.a
AS      firmware/sensorhub/shub_nacho_bl.bin.gen.o
AS      firmware/sensorhub/shub_nacho_a21s.bin.gen.o
AS      firmware/sensorhub/a21s_bring_up.bin.gen.o
AS      firmware/tsp_synaptics/td4150_a21s.bin.gen.o
AS      firmware/tsp_himax/hx83112a_a21s.bin.gen.o
```
Seems ok in kernel by samsung

**Comment by 0x454447415244** [comment]
I did lots of changes to compile. The last one was to comment the below lines:
```
fw-external-$(CONFIG_SENSORS_SSP) += sensorhub/shub_nacho_bl.bin
fw-external-$(CONFIG_SENSORS_SSP_A21S) += sensorhub/shub_nacho_a21s.bin
fw-external-$(CONFIG_SENSORS_SSP_A21S) += sensorhub/a21s_bring_up.bin
fw-external-$(CONFIG_TOUCHSCREEN_SYNAPTICS_TCM) += tsp_synaptics/td4150_a21s.bin
fw-external-$(CONFIG_TOUCHSCREEN_HIMAX_CHIPSET) += tsp_himax/hx83112a_a21s.bin
```

**Comment by yukosky** [comment]
Here I compiled all normal but, here I'm facing knox issues af

**Comment by 0x454447415244** [comment]
Make sure this is set:
CONFIG_KNOX_NCM=y

**Comment by yukosky** [comment]
> Make sure this is set:
> CONFIG_KNOX_NCM=y

Nah I want it disabled, I'll commit it and open the repo

**Comment by yukosky** [comment]
https://github.com/a2XX-dev/android_kernel_samsung_a21s-new/commit/a5924e7c0bff967d9368d4a25f034eb6723b28b8

**Comment by 0x454447415244** [comment]
I'll check your new repo. It should not be hard to disable KNOX.
I'm now trying to debug the error mentioned in my first post.

**Comment by yukosky** [comment]
> I'll check your new repo. It should not be hard to disable KNOX.
> I'm now trying to debug the error mentioned in my first post.

Nice, by the way try compiling w/o outdir, just use `make` and `make defconfig`, probably your issue will be gone or no

**Comment by 0x454447415244** [comment]
Yes, I'm compiling in the same directory. No luck for now getting the firmware files to work.

```
make[1]: *** No rule to make target 'firmware/sensorhub/shub_nacho_bl.bin', needed by 'firmware/sensorhub/shub_nacho_bl.bin.gen.o'.  Stop.
make: *** [Makefile:1153: firmware] Error 2

```

**Comment by yukosky** [comment]
> Yes, I'm compiling in the same directory. No luck for now getting the firmware files to work.
> 
> ```
> make[1]: *** No rule to make target 'firmware/sensorhub/shub_nacho_bl.bin', needed by 'firmware/sensorhub/shub_nacho_bl.bin.gen.o'.  Stop.
> make: *** [Makefile:1153: firmware] Error 2
> ```

Try compiling w/o outdir

**Comment by 0x454447415244** [comment]
Yes, this is what I'm doing already. Using the below to compile:
```
export CROSS_COMPILE="/mnt/SHARED/Phone/Samsung/A21S/gsi/kernel/aarch64-linux-android-4.9/bin/aarch64-linux-android-"
export ARCH=arm64
make ARCH=arm64 defconfig
make -j4
```

**Comment by yukosky** [comment]
New or old repo?

**Comment by 0x454447415244** [comment]
Still using the old repo...

**Comment by yukosky** [comment]
> Still using the old repo. Did you make changes related to the firmwares in the new one?

No

**Comment by 0x454447415244** [comment]
I got the same error with the new repo using your own build.sh script and toolchain.

```
  MK_FW   firmware/sensorhub/shub_nacho_bl.bin.gen.S
make[1]: *** No rule to make target 'firmware/sensorhub/shub_nacho_bl.bin', needed by 'firmware/sensorhub/shub_nacho_bl.bin.gen.o'.  Stop.
make: *** [Makefile:1143: firmware] Error 2
```

**Comment by yukosky** [comment]
> I got the same error with the new repo using your own build.sh script and toolchain.
> 
> ```
>   MK_FW   firmware/sensorhub/shub_nacho_bl.bin.gen.S
> make[1]: *** No rule to make target 'firmware/sensorhub/shub_nacho_bl.bin', needed by 'firmware/sensorhub/shub_nacho_bl.bin.gen.o'.  Stop.
> make: *** [Makefile:1143: firmware] Error 2
> ```

Here compile fine w/o problem, you're using some twrp/recovery/rom custom source?

**Comment by yukosky** [comment]
[a.txt](https://github.com/a2XX-dev/android_kernel_samsung_a21s/files/5752702/a.txt)

**Comment by 0x454447415244** [comment]
Could it be that you have some files in firmware directory that I don't have, possibly ignored with .gitignore ?

**Comment by yukosky** [comment]
> Could it be that you have some files in firmware directory that I don't have, possibly ignored with .gitignore ?

.gitignore don't exists in new/old repo of a21s kernel

**Comment by 0x454447415244** [comment]
> > Could it be that you have some files in firmware directory that I don't have, possibly ignored with .gitignore ?
> 
> .gitignore don't exists in new/old repo of a21s kernel

What about this one?
https://github.com/a2XX-dev/android_kernel_samsung_a21s/blob/master/firmware/.gitignore

**Comment by yukosky** [comment]
> > > Could it be that you have some files in firmware directory that I don't have, possibly ignored with .gitignore ?
> > 
> > 
> > .gitignore don't exists in new/old repo of a21s kernel
> 
> What about this one?
> https://github.com/a2XX-dev/android_kernel_samsung_a21s/blob/master/firmware/.gitignore

Ah, I see here, I'll add that files

**Comment by yukosky** [comment]
https://github.com/a2XX-dev/android_kernel_samsung_a21s-new/commit/58ba6ff74cffda22b998c93a54f40c0bb403a5f7

Check, maybe fixed now.

**Comment by 0x454447415244** [comment]
I added the files and it compiled as it should. However, when I repack boot.img (with magiskboot) and flash it the phone goes into boot loop. I'm using it along with official firmware files (or sometimes with custom SUPER partition). There are some DTB files along with the kernel image. Are you using any of them? (exynox, samsung). I'm using the DTB extracted with magiskboot but I don't think this is the problem.

Did you manage to flash this kernel successfully? What did you use?

**Comment by yukosky** [comment]
Bootloop is normal, need patch to fix it and idk which is. And the new is fine, only old no, that's why I bring-up other.

**Comment by yukosky** [comment]
So the problem is solved about `No rule to make target 'firmware/sensorhub/shub_nacho_bl.bin'`? @0x454447415244

**Comment by 0x454447415244** [comment]
Yes, it compiles. But the whole thing is useless. It never boots.
